name: ci
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  ps-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pester & PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module Pester -Force -Scope CurrentUser
          Install-Module PSScriptAnalyzer -Force -Scope CurrentUser
      - name: Lint
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path ./src -Recurse -Severity Warning -ReportSummary
      - name: Test
        shell: pwsh
        run: |
          Invoke-Pester -Path ./tests -CI -Output Detailed
